### PR TITLE
Use parser function to determine download candidate

### PR DESCRIPTION
**Pull request by mmarod**
Determine the latest version to download via a parser function... The parser function goes to http://files.nsclient.org/released/ and searches for the latest -- or supplied -- version in the target architecture.

### CODE REVIEW

**Comment by nibalizer** [comment]
This feels like a weird hack around ensure => latest. If we really are dynamically ensuring latest then we should make a resource that we can ensure => latest on. I also don't know enough about windows to say if this is truly upgradable.

Seems like a symver major change as well.

**Comment by mmarod** [comment]
I agree with you on the hacky bit -- But my intent was not to ensure latest on the package... It was to download either the latest version for the initial install without having to update the module every time a new version comes out. Looking at my code, however, I do now realize that every time a new version comes out that it will be downloaded even though it won't be installed. I could probably have download_file only run if the package "NSClient ++ " does not exist pretty easily though.

**Comment by bastelfreak** [comment]
HI @mmarod, thanks for the PR! Are you still interested in this and and to add logic to don't download the file on every release or should we close this PR?

**Comment by mmarod** [comment]
Sorry it has been so long since I put this code in that I have moved on. Revisiting it however, it looks like it should be fairly straightforward to have the module only download once by passing a ```destination_file``` parameter to the ```download_file``` type on [line 27 of the install class](https://github.com/mmarod/puppet-nsclient/blob/b7a19c567cf11f6121d6968f2265cb10b66158fc/manifests/install.pp#L27) that is static (ie NSCP.msi instead of NSCP-${version}-x64.msi). I'd make the change for you but I don't have a test environment anymore and thus wouldn't feel comfortable making changes.

Good luck and glad to see this module being looked at!

**Comment by mmarod** [comment]
... and if I misread your comment and you are going to instead not merge this code in that is fine with me as I am no longer using it

**Pull request closed without merging**
