### PR TITLE
release 2.1.0

### PR DESCRIPTION
**Pull request by Dan33l**

### CODE REVIEW

**Comment by Dan33l** [comment]
The module need https://github.com/voxpupuli/modulesync_config/pull/535 that fixes for the bundler stuff

**Comment by alexjfisher** [comment]
@Dan33l what’s the state of this?

**Comment by Dan33l** [comment]
Heu ... since it is merged, it should be possible to move forward.

**Comment by alexjfisher** [comment]
Would you like to rebase (if required) and regenerate the changelog? (For a more accurate release date).

**Comment by Dan33l** [comment]
It looks that `collaborators` can not merge. And so i can not apply `modulesync` on this module.

**Pull request merged**
