### PR TITLE
modulesync 2.12.0

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by bastelfreak** [comment]
no idea why it fails :(

**Comment by dhoppe** [comment]
> no idea why it fails :(

Maybe we should get rid of the downcase function, because it does not seem to be necessary:
https://github.com/camptocamp/facterdb/blob/master/facts/3.14/windows-2012%20r2-x86_64.facts#L119

We also should use the hash syntax for facts.

**Comment by ekohl** [comment]
Rebased and started fresh. The trick was in updating the spec files that set the facts.

**Comment by ekohl** [comment]
Ok, so locally I only tested with Puppet 6 and that passed. Didn't check with Puppet 5.

**Comment by ekohl** [comment]
:green_heart: by using rspec-puppet-facts.

**Pull request merged**
